
import java.awt.Color;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sanjay makwana
 */
public class LoanAssistant extends javax.swing.JFrame {

    private boolean computPayment;
    private Object computePayment;
    double loan;
    double interest;
    double month;
    double payment;
    double MonthlyPayment;
    
    public LoanAssistant() {
        initComponents();
        
       // XpaymentButton.doClick();
        XmonthButton.doClick();
        newLoanButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        computButton = new javax.swing.JButton();
        newLoanButton = new javax.swing.JButton();
        intersetTextField = new javax.swing.JTextField();
        balanceTextField = new javax.swing.JTextField();
        monthTextField = new javax.swing.JTextField();
        paymentTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        analysisTextAria = new javax.swing.JTextArea();
        XmonthButton = new javax.swing.JButton();
        XpaymentButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loan Assistant");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Loan Balance:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Interest Rate: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Number of Payment:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Monthly Payment:");

        computButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        computButton.setText("Compute Monthly Payment");
        computButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computButtonActionPerformed(evt);
            }
        });

        newLoanButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        newLoanButton.setText("New Loan Analysis");
        newLoanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newLoanButtonActionPerformed(evt);
            }
        });

        intersetTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        balanceTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        monthTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        paymentTextField.setBackground(new java.awt.Color(255, 255, 153));
        paymentTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        analysisTextAria.setBackground(new java.awt.Color(153, 153, 153));
        analysisTextAria.setColumns(20);
        analysisTextAria.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        analysisTextAria.setRows(5);
        jScrollPane1.setViewportView(analysisTextAria);

        XmonthButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        XmonthButton.setText("X");
        XmonthButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XmonthButtonActionPerformed(evt);
            }
        });

        XpaymentButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        XpaymentButton.setText("X");
        XpaymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XpaymentButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Loan Analysis");

        exitButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(newLoanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(102, 102, 102)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(intersetTextField)
                                    .addComponent(balanceTextField)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(paymentTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addComponent(monthTextField))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(XmonthButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(XpaymentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(computButton, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(balanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(intersetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(paymentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(XpaymentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(monthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(XmonthButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(computButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(15, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newLoanButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void newLoanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newLoanButtonActionPerformed
  
        
        balanceTextField.setText("");
        intersetTextField.setText("");
        paymentTextField.setText("");
        analysisTextAria.setText("");
        newLoanButton.setEnabled(false);
       computButton.setEnabled(true);
    }//GEN-LAST:event_newLoanButtonActionPerformed

    private void XpaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XpaymentButtonActionPerformed
       computePayment=true;
       XpaymentButton.setVisible(false);
       XmonthButton.setVisible(true);
       monthTextField.setEditable(true);
       monthTextField.setBackground(Color.WHITE);
       monthTextField.setFocusable(true);
       paymentTextField.setEditable(false);
       paymentTextField.setBackground(Color.YELLOW);
      paymentTextField.setFocusable(false);
      balanceTextField.requestFocus();
       
    }//GEN-LAST:event_XpaymentButtonActionPerformed

    private void XmonthButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XmonthButtonActionPerformed
      computePayment = false;
      XpaymentButton.setVisible(true);
      XmonthButton.setVisible(false);
      monthTextField.setEditable(false);
      monthTextField.setBackground(Color.YELLOW);
      monthTextField.setFocusable(false);
      paymentTextField.setEditable(true);
      paymentTextField.setBackground(Color.WHITE);
      paymentTextField.setFocusable(true);
      balanceTextField.requestFocus();
      computButton.setVisible(true);
     
    }//GEN-LAST:event_XmonthButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed

       int diag = JOptionPane.showConfirmDialog(null,"Do You Want To Exit ?");
        if(diag == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
        else
        {
            
        }
    }//GEN-LAST:event_exitButtonActionPerformed

    private void computButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computButtonActionPerformed
       
        //Compute The Loan Payment
        
        String iMonthPayment = String.format(monthTextField.getText());
        
        if(balanceTextField.getText().equals("")){
            JOptionPane.showMessageDialog(null,"You Must Enter Amount Of Balance !",
                    "Loan System",JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            loan = Double.parseDouble(balanceTextField.getText());
            String Balance = String.format(balanceTextField.getText());
        }
        if(intersetTextField.getText().equals("")){
            JOptionPane.showMessageDialog(null,"You Must Enter Amount Of Interest Rate !",
                    "Loan System",JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            interest = Double.parseDouble(intersetTextField.getText());
            String iInterest = String.format(intersetTextField.getText());
        }
           
        if(paymentTextField.getText().equals("")){
            JOptionPane.showMessageDialog(null,"You Must Enter Amount Of Number of Payment !",
                    "Loan System",JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            month = Double.parseDouble(paymentTextField.getText());
            String iMonth = String.format(paymentTextField.getText());
        }
         
        payment = loan + ((loan * interest)/100);
        
        MonthlyPayment = payment / month;
        String PayMonth = String.format("%.2f",MonthlyPayment);
        monthTextField.setText(PayMonth);
        analysisTextAria.append("\t\n Loan Assistan Project:\n\n"+"Amoun of Loan:\t\t $"+ loan +"\n Number of Payment:\t\t $"+ interest+"\nMonthly Payment:\t\t $" + month+ "\nPayment Per Month:\t\t $" +MonthlyPayment+ "\nTotal Loan Payment:\t\t $" +payment+ "\n\nThanks for using Sanjay's Loan System");
        newLoanButton.setEnabled(true);
       computButton.setEnabled(false);
    }//GEN-LAST:event_computButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanAssistant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanAssistant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanAssistant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanAssistant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanAssistant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton XmonthButton;
    private javax.swing.JButton XpaymentButton;
    private javax.swing.JTextArea analysisTextAria;
    private javax.swing.JTextField balanceTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton computButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JTextField intersetTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField monthTextField;
    private javax.swing.JButton newLoanButton;
    private javax.swing.JTextField paymentTextField;
    // End of variables declaration//GEN-END:variables
}
